# -*- coding: utf-8 -*-
"""SVM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VmxZSjAx5z8ALqj8Kagj8JdCoVC1MRkU
"""

import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_digits
from sklearn import svm
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score

data = load_digits()
print(data.images[0])
print(len(data.images[0]))
print(data.images[0].shape)
print(data.target)
print(data.target.size)
plt.gray()
plt.imshow(data.images[0])

X = data.images.reshape(len(data.images), -1)
y = data.target
print(X.shape)
print(y.shape)

X_train, X_test, y_train, y_test = train_test_split(X,y)
print(X_train.shape)
print(X_test.shape)

kgm = np.arange(0.001,0.02,0.001)
accuracies = []
accuracies1 = []
for k in kgm:
 svc = svm.SVC(gamma = k, C = 100)
 svc.fit(X_train,y_train)
 pred = svc.predict(X_test)
 acc = accuracy_score(y_test, pred)
 accuracies.append(acc)
 pred1 = svc.predict(X_train)
 acc1 = accuracy_score(y_train, pred1)
 accuracies1.append(acc1)
 print("gamma = "+ str(k)+"; Accuracy: "+str(acc))

plt.plot(kgm, accuracies, 'g-', label='Test accuracy')
plt.plot(kgm, accuracies1, 'g--', label='Train accuracy')
plt.legend(['Test accuracy ', 'Train accuracy'])
plt.xlabel("Gamma")
plt.ylabel("Accuracy")
plt.savefig('_model.png')